name: Snyk Security CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm i -g snyk
      - run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: install snyk-to-html
        run: |
          npm install snyk-to-html -g
          snyk test --json | snyk-to-html -o result.html
      - name: Snyk Open Source # For testing and failing please add snyk test before snyk monitor
        run: |
          snyk test || true
          
      - name: Snyk Code # Remove || true to fail if there are vulnerabilities
        run: |
          snyk code test --json | snyk-to-html -o results-code.html || true

      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: results-code
          path: results-code.html
      
      - name: Snyk IaC # Remove || true to fail if there are vulnerabilities
        run: |
         snyk iac test --report || true
     
      - name: Snyk Container # Rename your image, for testing and failing please add snyk container test before snyk container monitor
        run: |
          snyk container test freshdemo/juice-shop-github-dockerhub-gke:actions --file=Dockerfile || true
          
#      - name: Use the Upload Artifact GitHub Action
#        uses: actions/upload-artifact@v2
#        with:
#          name: results-code
#          path: results-code.html
